#!/bin/bash
#PBS -N pmpaths
#PBS -e errlog
#PBS -o output
#PBS -l feature=16core
#PBS -l nodes=4:ppn=16
#PBS -q short
#PBS -A NRELMatDB
#PBS -l walltime=00:40:00

deactivate

source /projects/NRELMatDB/pylada-light/pylada-light/peregrine-env.sh

module unload mpi/impi-intel/4.1.0.024

rm -f timefile

cp PARAM $(mktemp -u PARAM.old.XXXXX)

cp empty.PARAM PARAM

## This will reproduce the output used to create the plots in the report
# for i in $(seq 3)
# do
#     for j in $(seq 3)
#     do
# 	if [ $i != $j ]; then
# 	echo -e "POSCAR_test_${j},POSCAR_test_${i},,,,traj_testing${i}${j},,,3.6,101,,,,1,0.3" >> PARAM
# 	srun -n 1 python fastpmpaths.py --param
# 	srun -n 2 python fastpmpaths.py --param
# 	srun -n 4 python fastpmpaths.py --param
# 	srun -n 8 python fastpmpaths.py --param
# 	srun -n 16 python fastpmpaths.py --param
# 	srun -n 32 python fastpmpaths.py --param
# 	srun -n 64 python fastpmpaths.py --param
# 	fi
#     done
# done


##This is a single call of fastpmpaths with one job and 16 processors
echo -e "POSCAR_test_1,POSCAR_test_2,,,,traj_testing12,,,3.6,101,,,,1,0.3," >> PARAM
mpirun -n 64  python fastpmpaths.py --param