#!/bin/bash
#PBS -N pmpaths
#PBS -e errlog
#PBS -o output
#PBS -l feature=24core
#PBS -l nodes=6:ppn=24
#PBS -q short
#PBS -A NRELMatDB
#PBS -l walltime=00:40:00

cd /scratch/felixt/polymorph

deactivate

source /projects/NRELMatDB/pylada-light/pylada-light/peregrine-env.sh

module unload mpi/impi-intel/4.1.0.024

rm -f timefile

#cp PARAM $(mktemp -u PARAM.old.XXXXX)

#cp empty.PARAM PARAM

mpirun -n 144 python fastpmpaths.py --param