#!/bin/bash

cp PARAM '#PARAM#'

cp empty.PARAM PARAM

while read transition || [[ -n "$transition" ]]; do
    echo "TestDir/examples/$transition/POSCAR_A,TestDir/examples/$transition/POSCAR_B,3,,,TestDir/examples/$transition/A2B_test,,,3.6,101,,,1,1,0.3," >> PARAM
    echo "TestDir/examples/$transition/POSCAR_B,TestDir/examples/$transition/POSCAR_A,3,,,TestDir/examples/$transition/B2A_test,,,3.6,101,,,1,1,0.3," >> PARAM
done < TestDir/ExampleList

if [ "$1" = "" ]; then
    n=2
else
    n=$1
fi

echo "Running fastpmpaths with $n processor(s)"

mpirun -n $n python fastpmpaths.py --param

done < TestDir/ExampleList

echo "Comparing with expected results"

cd ./TestDir

python compare.py

cp empty.PARAM PARAM
